name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋 歡迎你的 Issue！請提供詳細的描述，以便更好地協助你 "
        pr-message: "🎉 感謝你的 PR！我們會儘快進行審查 "
